[package]
name = "snake2"
version = "0.1.0"
authors = ["cjddaniels <cameronjddaniels@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
ndarray = "0.15.1"
rand = "0.8.3"
